# DOCS: https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/
# DOCS: https://docs.docker.com/engine/reference/builder/

FROM alpine:latest
WORKDIR /

# copy test app
ARG TEST
ADD ${TEST} .

# CMD does not expand ARG
USER nobody:nobody
ENV  TEST=${TEST}
CMD  exec ./${TEST}
